spring:
  datasource:
    master:
      hikari:
        username: rapakitchen_rw
        password: kakaoPass123#
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.250.177:3306/rapakitchen?serverTimezone=Asia/Seoul
    slave:
      hikari:
        username: rapakitchen_ro
        password: kakaoPass123#
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.251.22:3306/rapakitchen?serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


