apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapa-frontend-deploy
  namespace: rapa-app-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rapa-client
  template:
    metadata:
      name: rapa-frontend-pod
      labels:
        app: rapa-client
    spec:
      containers:
      - name: rapa-frontend
        image: jjy9922/rapa-react:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-end-hpa
  namespace: rapa-app-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: front-end-deployment
  minReplicas: 1 
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80 # define the replicas range and the scaling policy for the deployment
---
apiVersion: v1
kind: Service
metadata:
  name: rapa-frontend-service
  namespace: rapa-app-ns 
spec:
  type: NodePort 
  selector:
    app: rapa-client 
  ports:
  - port: 3000 
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: rapa-app-ns
  name: ingress-front-end
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip # using IP routing policy of ALB
    alb.ingress.kubernetes.io/subnets: $WorkerSubnetPublic1, $WorkerSubnetPublic2, $WorkerSubnetPublic3, $WorkerSubnetPublic4
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rapa-frontend-service # refer to the service defined in deploy.yaml
                port:
                  number: 3000
